USE alx_book_store;

SHOW COLUMNS FROM alx_book_store;

SELECT 
    COLUMN_NAME, 
    DATA_TYPE,
    COLUMN_TYPE
FROM
    INFORMATION_SCHEMA.COLUMNS
WHERE
    TABLE_SCHEMA = 'alx_book_store' AND TABLE_NAME = 'Books';